name: Build Packages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  EGNITE_BUILD_DEPS: TRUE

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest

    strategy:
      matrix:
        build_type: [Release]
        c_compiler: gcc
        cpp_compiler: g++
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install \
            libcurl4-openssl-dev \
            libgl1-mesa-dev \
            libxcb-cursor0 \
            libxcb-icccm4 \
            libxcb-image0 \
            libxcb-keysyms1 \
            libxcb-randr0 \
            libxcb-render-util0 \
            libxcb-shape0 \
            libxcb-xinerama0 \
            libxkbcommon-x11-0 \
            libzstd-dev

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1
        with:
          max-size: 250M

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          cmake-version: '3.19'

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

  windows:
    name: Windows
    runs-on: windows-latest

    strategy:
      matrix:
        build_type: [Release]
        c_compiler: cl
        cpp_compiler: cl
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_CXX_COMPILER=${{ matrix.cpp_compiler }}
          -DCMAKE_C_COMPILER=${{ matrix.c_compiler }}
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -S ${{ github.workspace }}

      - name: Build
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
